import type { Metadata } from "next";
import "./globals.css";
import Background from "@/components/background";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Technologies from "@/components/Technologies";
import Contact from "@/components/Contact";
import Projects from "@/components/Projects";

export const metadata: Metadata = {
  title: "Portfolio - Saish Ghatol",
  description: "Generated by create next app with TypeScript, Tailwind CSS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-sans">
        <Background>
          <Navbar/>
          <Hero/>
          <Technologies/>
          <Projects/>
          <Contact/>
          {children}
        </Background>        
      </body>
    </html>
  );
}