import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import  Background  from "@/components/background";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Technologies from "@/components/Technologies";
import Contact from "@/components/Contact";
import Projects from "@/components/Projects";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
  weight: "variable"
});

export const metadata: Metadata = {
  title: "Portfolio - Saish Ghatol",
  description: "Generated by create next app with TypeScript, Tailwind CSS",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jetbrainsMono.variable} font-sans`}>
        <Background>
          <Navbar/>
          <Hero/>
          <Technologies/>
          <Projects/>
          <Contact/>
         {children}
        </Background>        
      </body>
    </html>
  );
}